version: '3.8'

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    restart: always

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env

# Comment out Celery services
# celery_worker:
#   build: .
#   command: bash -c "sleep 10 && celery -A sports_booking worker --loglevel=info"
#   volumes:
#     - .:/app
#   depends_on:
#     - web
#     - redis
#   env_file: .env

# celery_beat:
#   build: .
#   command: bash -c "sleep 10 && celery -A sports_booking beat --loglevel=info"
#   volumes:
#     - .:/app
#   depends_on:
#     - web
#     - redis
#   env_file: .env

volumes:
  postgres_data:
